/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Color;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import Controllers.AdminController;
import Controllers.GlobalController;
import Models.AdminModel;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author benza
 */
public class AdminDashboardView extends javax.swing.JFrame {

    private Connection con;
    
    //cashier management 
    private JFileChooser newCashierPic;
    private int prefixCashierMenu;
    
    /**
     * Creates new form LoginView
     */
    public AdminDashboardView(Connection con, AdminModel admin) {
        initComponents();
        setTitle("POS");
        setLocationRelativeTo(null);
        URL iconURL = getClass().getResource("/Assets/favico.png");
        if(iconURL != null){
            setIconImage(new ImageIcon(iconURL).getImage());
        }
        setVisible(true);
        this.con=con;
        updateAdminMenu(admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputAddCashierSex = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tabbedMenu = new javax.swing.JTabbedPane();
        adminMenu = new javax.swing.JPanel();
        menuName = new javax.swing.JLabel();
        itemAdd = new javax.swing.JButton();
        adminMenuPic = new javax.swing.JLabel();
        adminMenuLastName = new javax.swing.JLabel();
        adminMenuFirstName = new javax.swing.JLabel();
        adminMenuPosition = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cashierMenu = new javax.swing.JPanel();
        menuName1 = new javax.swing.JLabel();
        itemAdd1 = new javax.swing.JButton();
        cashierMenuNavLeft = new javax.swing.JButton();
        cashierMenuNavRight = new javax.swing.JButton();
        cashierMenuCashier1Pic = new javax.swing.JLabel();
        cashierMenuCashier1 = new javax.swing.JLabel();
        cashierMenuCashier1Info = new javax.swing.JLabel();
        cashierMenuViewCashier1 = new javax.swing.JButton();
        cashierMenuCashier2Pic = new javax.swing.JLabel();
        cashierMenuCashier2 = new javax.swing.JLabel();
        cashierMenuCashier2Info = new javax.swing.JLabel();
        cashierMenuViewCashier2 = new javax.swing.JButton();
        cashierMenuCashier3Pic = new javax.swing.JLabel();
        cashierMenuCashier3 = new javax.swing.JLabel();
        cashierMenuCashier3Info = new javax.swing.JLabel();
        cashierMenuViewCashier3 = new javax.swing.JButton();
        cashierMenuCashier4Pic = new javax.swing.JLabel();
        cashierMenuCashier4 = new javax.swing.JLabel();
        cashierMenuCashier4Info = new javax.swing.JLabel();
        cashierMenuViewCashier4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        kGradientPanel4 = new com.k33ptoo.components.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        tabbedPreview = new javax.swing.JTabbedPane();
        addCashier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputAddCashierLastName = new javax.swing.JTextField();
        inputAddCashierFirstName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputAddCashierEmail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        inputAddCashierPhone = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        inputAddCashierPassword = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        submitAddCashier = new javax.swing.JButton();
        inputAddCashierSalary = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        inputAddCashierMale = new javax.swing.JRadioButton();
        inputAddCashierFemale = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        pictureUploadAddCashier = new javax.swing.JButton();
        flashAddCashier = new javax.swing.JLabel();
        inputAddCashierEndDate = new com.toedter.calendar.JDateChooser();
        inputAddCashierStartDate = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 960));
        setMinimumSize(new java.awt.Dimension(1024, 768));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedMenu.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        menuName.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        menuName.setText("Admin");

        itemAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/edit.png"))); // NOI18N

        adminMenuLastName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adminMenuLastName.setText("Last Name");

        adminMenuFirstName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adminMenuFirstName.setText("First Name");

        adminMenuPosition.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        adminMenuPosition.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminMenuPosition.setText("Position");
        adminMenuPosition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("― Roy T. Bennett, The Light in the Heart");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("“Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.”");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout adminMenuLayout = new javax.swing.GroupLayout(adminMenu);
        adminMenu.setLayout(adminMenuLayout);
        adminMenuLayout.setHorizontalGroup(
            adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuLayout.createSequentialGroup()
                .addGroup(adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminMenuLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminMenuPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(adminMenuLayout.createSequentialGroup()
                                    .addComponent(adminMenuPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adminMenuLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adminMenuFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(adminMenuLayout.createSequentialGroup()
                                    .addComponent(menuName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(itemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        adminMenuLayout.setVerticalGroup(
            adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(menuName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(adminMenuPosition)
                .addGap(37, 37, 37)
                .addGroup(adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminMenuPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminMenuLayout.createSequentialGroup()
                        .addComponent(adminMenuLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminMenuFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tabbedMenu.addTab("tab3", adminMenu);

        menuName1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        menuName1.setText("Cashiers");

        itemAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/plus.png"))); // NOI18N
        itemAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdd1ActionPerformed(evt);
            }
        });

        cashierMenuNavLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/nav_prev.png"))); // NOI18N
        cashierMenuNavLeft.setEnabled(false);
        cashierMenuNavLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierMenuNavLeftActionPerformed(evt);
            }
        });

        cashierMenuNavRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/nav_next.png"))); // NOI18N
        cashierMenuNavRight.setEnabled(false);
        cashierMenuNavRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierMenuNavRightActionPerformed(evt);
            }
        });

        cashierMenuCashier1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cashierMenuCashier1.setText("prev");

        cashierMenuCashier1Info.setText("jLabel5");

        cashierMenuViewCashier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/manage.png"))); // NOI18N
        cashierMenuViewCashier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierMenuViewCashier1ActionPerformed(evt);
            }
        });

        cashierMenuCashier2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cashierMenuCashier2.setText("qfd");

        cashierMenuCashier2Info.setText("jLabel5");

        cashierMenuViewCashier2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/manage.png"))); // NOI18N

        cashierMenuCashier3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cashierMenuCashier3.setText("jLabel4");

        cashierMenuCashier3Info.setText("jLabel5");

        cashierMenuViewCashier3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/manage.png"))); // NOI18N

        cashierMenuCashier4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cashierMenuCashier4.setText("jLabel4");

        cashierMenuCashier4Info.setText("jLabel5");

        cashierMenuViewCashier4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/manage.png"))); // NOI18N

        javax.swing.GroupLayout cashierMenuLayout = new javax.swing.GroupLayout(cashierMenu);
        cashierMenu.setLayout(cashierMenuLayout);
        cashierMenuLayout.setHorizontalGroup(
            cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashierMenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuCashier1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cashierMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cashierMenuCashier1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashierMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cashierMenuCashier1Info, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(cashierMenuViewCashier1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cashierMenuLayout.createSequentialGroup()
                                .addComponent(cashierMenuCashier4Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cashierMenuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cashierMenuCashier4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(cashierMenuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cashierMenuCashier4Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(cashierMenuViewCashier4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cashierMenuLayout.createSequentialGroup()
                                .addComponent(cashierMenuCashier3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cashierMenuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cashierMenuCashier3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(cashierMenuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cashierMenuCashier3Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(cashierMenuViewCashier3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cashierMenuLayout.createSequentialGroup()
                                .addComponent(cashierMenuCashier2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cashierMenuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cashierMenuCashier2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(cashierMenuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cashierMenuCashier2Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(cashierMenuViewCashier2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
            .addGroup(cashierMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuNavLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cashierMenuNavRight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(menuName1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        cashierMenuLayout.setVerticalGroup(
            cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashierMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuName1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashierMenuNavLeft)
                    .addComponent(cashierMenuNavRight))
                .addGap(49, 49, 49)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashierMenuCashier1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuCashier1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashierMenuCashier1Info))
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cashierMenuViewCashier1)))
                .addGap(42, 42, 42)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashierMenuCashier2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuCashier2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashierMenuCashier2Info))
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cashierMenuViewCashier2)))
                .addGap(42, 42, 42)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashierMenuCashier3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuCashier3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashierMenuCashier3Info))
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cashierMenuViewCashier3)))
                .addGap(42, 42, 42)
                .addGroup(cashierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuCashier4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashierMenuCashier4Info))
                    .addComponent(cashierMenuCashier4Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cashierMenuLayout.createSequentialGroup()
                        .addComponent(cashierMenuViewCashier4)
                        .addGap(11, 11, 11)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tabbedMenu.addTab("tab3", cashierMenu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        tabbedMenu.addTab("tab4", jPanel4);

        jPanel1.add(tabbedMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 620));

        kGradientPanel4.setkBorderRadius(30);
        kGradientPanel4.setkEndColor(new java.awt.Color(30, 32, 44));
        kGradientPanel4.setkStartColor(new java.awt.Color(30, 32, 44));

        jButton1.setBackground(new java.awt.Color(30, 32, 44));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/admin.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(30, 32, 44));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cashier.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGradientPanel3.setkBorderRadius(100);
        kGradientPanel3.setkEndColor(new java.awt.Color(30, 32, 44));
        kGradientPanel3.setkStartColor(new java.awt.Color(30, 32, 44));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPreview.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        addCashier.setBackground(new java.awt.Color(30, 32, 44));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Register a new Cashier");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Cashier into");

        kGradientPanel1.setBackground(new java.awt.Color(30, 32, 44));
        kGradientPanel1.setkBorderRadius(100);
        kGradientPanel1.setkEndColor(new java.awt.Color(41, 43, 55));
        kGradientPanel1.setkStartColor(new java.awt.Color(41, 43, 55));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Last Name");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Email");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setText("Phone");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setText("Password");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setText("Start Date");

        jLabel27.setText("Contract information");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setText("End Date");

        submitAddCashier.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitAddCashier.setText("SAVE");
        submitAddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddCashierActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setText("Salary");

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setText("Sex");

        inputAddCashierSex.add(inputAddCashierMale);
        inputAddCashierMale.setText("Male");

        inputAddCashierSex.add(inputAddCashierFemale);
        inputAddCashierFemale.setText("Female");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setText("Picture");

        pictureUploadAddCashier.setText("Select");
        pictureUploadAddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureUploadAddCashierActionPerformed(evt);
            }
        });

        flashAddCashier.setForeground(new java.awt.Color(255, 0, 51));
        flashAddCashier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        inputAddCashierEndDate.setDateFormatString("yyyy-MM-dd");

        inputAddCashierStartDate.setForeground(new java.awt.Color(255, 255, 255));
        inputAddCashierStartDate.setToolTipText("");
        inputAddCashierStartDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputAddCashierMale)
                        .addGap(18, 18, 18)
                        .addComponent(inputAddCashierFemale)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputAddCashierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputAddCashierPhone)))
                                .addGap(33, 33, 33)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pictureUploadAddCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputAddCashierPassword))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputAddCashierFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputAddCashierLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(flashAddCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(submitAddCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputAddCashierStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputAddCashierEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputAddCashierSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAddCashierLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(inputAddCashierFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAddCashierEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAddCashierPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputAddCashierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pictureUploadAddCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputAddCashierMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputAddCashierFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputAddCashierEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAddCashierStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAddCashierSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitAddCashier, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flashAddCashier, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout addCashierLayout = new javax.swing.GroupLayout(addCashier);
        addCashier.setLayout(addCashierLayout);
        addCashierLayout.setHorizontalGroup(
            addCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashierLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(addCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        addCashierLayout.setVerticalGroup(
            addCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashierLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tabbedPreview.addTab("tab1", addCashier);

        jPanel6.setBackground(new java.awt.Color(30, 32, 44));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );

        tabbedPreview.addTab("tab2", jPanel6);

        tabbedPreview.setSelectedIndex(1);

        jPanel3.add(tabbedPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 810));

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(948, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(664, Short.MAX_VALUE)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(152, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tabbedMenu.setSelectedIndex(1);
        prefixCashierMenu=0;
        try{
            fillCashierMenu(new AdminController(this.con).getCashiers(prefixCashierMenu));
        }catch(SQLException ex){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tabbedMenu.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitAddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAddCashierActionPerformed
        // TODO add your handling code here:
        ArrayList textfields= new ArrayList();
        textfields.add(inputAddCashierFirstName);
        textfields.add(inputAddCashierLastName);
        textfields.add(inputAddCashierEmail);
        textfields.add(inputAddCashierPassword);
        textfields.add(inputAddCashierPhone);
        textfields.add(inputAddCashierSalary);
        ArrayList intfields= new ArrayList();
        intfields.add(inputAddCashierPhone);
        intfields.add(inputAddCashierSalary);
        ArrayList datefields= new ArrayList();
        datefields.add(inputAddCashierStartDate.getDate());
        datefields.add(inputAddCashierEndDate.getDate());
        ArrayList filefields= new ArrayList();
        filefields.add(newCashierPic);
        java.sql.Date sd,ed;
        String sex="";
        if(inputAddCashierMale.isSelected()){
            sex="M";
        }else if(inputAddCashierFemale.isSelected()){
            sex="F";
        }
        if(!sex.isEmpty()){
            try{
                if(GlobalController.checkInputFields(textfields) && GlobalController.checkInputFieldsNumeric(intfields) && GlobalController.checkInputFieldsDate(datefields) && GlobalController.checkinputFieldsPicture(filefields)){
                    try{
                        byte[] picture=null;
                        String filename="cashiers\\"+inputAddCashierEmail.getText().trim()+GlobalController.getExtension(newCashierPic.getSelectedFile());
                        FileInputStream fis= new FileInputStream(newCashierPic.getSelectedFile());
                        ByteArrayOutputStream bos= new ByteArrayOutputStream();
                        FileOutputStream fos= new FileOutputStream(filename);
                        byte[] buf =new byte[1024];
                        for(int readNum; (readNum=fis.read(buf))!=-1;){
                            bos.write(buf,0,readNum);
                        }
                        bos.writeTo(fos);
                        fos.flush();
                        sd = new java.sql.Date(inputAddCashierStartDate.getDate().getTime());
                        ed = new java.sql.Date(inputAddCashierEndDate.getDate().getTime());
                        new AdminController(this.con).registerCashier(
                                inputAddCashierFirstName.getText().trim(),
                                inputAddCashierLastName.getText().trim(),
                                inputAddCashierEmail.getText().trim(),
                                inputAddCashierPhone.getText().trim(),
                                sex,
                                filename,
                                inputAddCashierPassword.getText().trim(),
                                sd,
                                ed,
                                Integer.parseInt(inputAddCashierSalary.getText()));
                        flashAddCashier.setText("Cashier Registered.");
                        fillCashierMenu(new AdminController(this.con).getCashiers(prefixCashierMenu));
                    }catch(SQLException ex){
                        flashAddCashier.setText(ex.getMessage());
                    }catch(Exception e){
                        flashAddCashier.setText("File upload Error!");
                    }
                }else{
                    flashAddCashier.setText("All fields required!");
                }
            }catch(NullPointerException ex){
                flashAddCashier.setText("All fields required!");
            }
        }
    }//GEN-LAST:event_submitAddCashierActionPerformed

    private void itemAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdd1ActionPerformed
        // TODO add your handling code here:
        tabbedPreview.setSelectedIndex(0);
    }//GEN-LAST:event_itemAdd1ActionPerformed

    private void cashierMenuViewCashier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierMenuViewCashier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashierMenuViewCashier1ActionPerformed

    private void pictureUploadAddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureUploadAddCashierActionPerformed
        // TODO add your handling code here:
        newCashierPic = new JFileChooser();
        newCashierPic.showOpenDialog(null);
    }//GEN-LAST:event_pictureUploadAddCashierActionPerformed

    private void cashierMenuNavRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierMenuNavRightActionPerformed
        // TODO add your handling code here:
        cashierMenuNavLeft.setEnabled(true);
        prefixCashierMenu++;
        try{
            fillCashierMenu(new AdminController(this.con).getCashiers(prefixCashierMenu));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Please fill all the fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cashierMenuNavRightActionPerformed

    private void cashierMenuNavLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierMenuNavLeftActionPerformed
        // TODO add your handling code here:
        prefixCashierMenu--;
        try{
            fillCashierMenu(new AdminController(this.con).getCashiers(prefixCashierMenu));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Please fill all the fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(prefixCashierMenu==0){
            cashierMenuNavLeft.setEnabled(false);
        }
    }//GEN-LAST:event_cashierMenuNavLeftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addCashier;
    private javax.swing.JPanel adminMenu;
    private javax.swing.JLabel adminMenuFirstName;
    private javax.swing.JLabel adminMenuLastName;
    private javax.swing.JLabel adminMenuPic;
    private javax.swing.JLabel adminMenuPosition;
    private javax.swing.JPanel cashierMenu;
    private javax.swing.JLabel cashierMenuCashier1;
    private javax.swing.JLabel cashierMenuCashier1Info;
    private javax.swing.JLabel cashierMenuCashier1Pic;
    private javax.swing.JLabel cashierMenuCashier2;
    private javax.swing.JLabel cashierMenuCashier2Info;
    private javax.swing.JLabel cashierMenuCashier2Pic;
    private javax.swing.JLabel cashierMenuCashier3;
    private javax.swing.JLabel cashierMenuCashier3Info;
    private javax.swing.JLabel cashierMenuCashier3Pic;
    private javax.swing.JLabel cashierMenuCashier4;
    private javax.swing.JLabel cashierMenuCashier4Info;
    private javax.swing.JLabel cashierMenuCashier4Pic;
    private javax.swing.JButton cashierMenuNavLeft;
    private javax.swing.JButton cashierMenuNavRight;
    private javax.swing.JButton cashierMenuViewCashier1;
    private javax.swing.JButton cashierMenuViewCashier2;
    private javax.swing.JButton cashierMenuViewCashier3;
    private javax.swing.JButton cashierMenuViewCashier4;
    private javax.swing.JLabel flashAddCashier;
    private javax.swing.JTextField inputAddCashierEmail;
    private com.toedter.calendar.JDateChooser inputAddCashierEndDate;
    private javax.swing.JRadioButton inputAddCashierFemale;
    private javax.swing.JTextField inputAddCashierFirstName;
    private javax.swing.JTextField inputAddCashierLastName;
    private javax.swing.JRadioButton inputAddCashierMale;
    private javax.swing.JPasswordField inputAddCashierPassword;
    private javax.swing.JTextField inputAddCashierPhone;
    private javax.swing.JTextField inputAddCashierSalary;
    private javax.swing.ButtonGroup inputAddCashierSex;
    private com.toedter.calendar.JDateChooser inputAddCashierStartDate;
    private javax.swing.JButton itemAdd;
    private javax.swing.JButton itemAdd1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel menuName;
    private javax.swing.JLabel menuName1;
    private javax.swing.JButton pictureUploadAddCashier;
    private javax.swing.JButton submitAddCashier;
    private javax.swing.JTabbedPane tabbedMenu;
    private javax.swing.JTabbedPane tabbedPreview;
    // End of variables declaration//GEN-END:variables

    private void fillCashierMenu(ResultSet data){
        try{
            if(data.next()){
                cashierMenuCashier1.setText(data.getString("firstname")+" "+data.getString("lastname"));
                cashierMenuCashier1Info.setText("soon!");
                cashierMenuCashier1Pic.setIcon(new ImageIcon(new ImageIcon(data.getString("pictureurl")).getImage().getScaledInstance(cashierMenuCashier1Pic.getWidth(),cashierMenuCashier1Pic.getHeight(),Image.SCALE_SMOOTH)));
                cashierMenuViewCashier1.setVisible(true);
                cashierMenuNavRight.setEnabled(true);
            }else{
                cashierMenuCashier1.setText("");
                cashierMenuCashier1Info.setText("");
                cashierMenuViewCashier1.setVisible(false);
                cashierMenuNavRight.setEnabled(false);
                cashierMenuCashier1Pic.setIcon(null);
            }

            if(data.next()){
                cashierMenuCashier2.setText(data.getString("firstname")+" "+data.getString("lastname"));
                cashierMenuCashier2Info.setText("soon!");
                cashierMenuCashier2Pic.setIcon(new ImageIcon(new ImageIcon(data.getString("pictureurl")).getImage().getScaledInstance(cashierMenuCashier2Pic.getWidth(),cashierMenuCashier2Pic.getHeight(),Image.SCALE_DEFAULT)));
                cashierMenuViewCashier2.setVisible(true);
                cashierMenuNavRight.setEnabled(true);
            }else{
                cashierMenuCashier2.setText("");
                cashierMenuCashier2Info.setText("");
                cashierMenuViewCashier2.setVisible(false);
                cashierMenuNavRight.setEnabled(false);
                cashierMenuCashier2Pic.setIcon(null);
            }

            if(data.next()){
                cashierMenuCashier3.setText(data.getString("firstname")+" "+data.getString("lastname"));
                cashierMenuCashier3Info.setText("soon!");
                cashierMenuCashier3Pic.setIcon(new ImageIcon(new ImageIcon(data.getString("pictureurl")).getImage().getScaledInstance(cashierMenuCashier3Pic.getWidth(),cashierMenuCashier3Pic.getHeight(),Image.SCALE_DEFAULT)));
                cashierMenuViewCashier3.setVisible(true);
                cashierMenuNavRight.setEnabled(true);
            }else{
                cashierMenuCashier3.setText("");
                cashierMenuCashier3Info.setText("");
                cashierMenuViewCashier3.setVisible(false);
                cashierMenuNavRight.setEnabled(false);
                cashierMenuCashier3Pic.setIcon(null);
            }

            if(data.next()){
                cashierMenuCashier4.setText(data.getString("firstname")+" "+data.getString("lastname"));
                cashierMenuCashier4Info.setText("soon!");
                cashierMenuCashier4Pic.setIcon(new ImageIcon(new ImageIcon(data.getString("pictureurl")).getImage().getScaledInstance(cashierMenuCashier4Pic.getWidth(),cashierMenuCashier4Pic.getHeight(),Image.SCALE_DEFAULT)));
                cashierMenuViewCashier4.setVisible(true);
                cashierMenuNavRight.setEnabled(true);
            }else{
                cashierMenuCashier4.setText("");
                cashierMenuCashier4Info.setText("");
                cashierMenuViewCashier4.setVisible(false);
                cashierMenuNavRight.setEnabled(false);
                cashierMenuCashier4Pic.setIcon(null);
            }
        }catch(SQLException ex){
            
        }
    }
    
    private void updateAdminMenu(AdminModel admin){
        adminMenuFirstName.setText(admin.firstname);
        adminMenuLastName.setText(admin.lastname);
        adminMenuPosition.setText(admin.position);
    }
}
